# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scifi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql


class Ui_Form(object):
    def messagebox(self,title,message):
        mess=QtWidgets.QMessageBox()
        mess.setWindowTitle(title)
        mess.setStandardButtons(QtWidgets,QMessagebox.Ok)
        mess.exec_()
    def signup(self):
        name=self.lineEdit.text()
        location=self.lineEdit_2.text()
        mail_id=self.lineEdit_3.text()
        conn=pymysql.connect(  host="localhost",user="root",passwd="milan",database="OLIVIA_DB",auth_plugin = 'mysql_native_password')
        cur=conn.cursor()
        query=("insert into user_details(name,location,mail_id) values(%s,%s,%s,%s)")
        data=cur.execute(query,(name,location,email_id))
        if(data):
            self.messagebox("congrats","data stored")
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/redc/lib/tuse.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(580, 290, 821, 461))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/redc/lib/"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 391, 71))
        self.label_5.setObjectName("label_5")
        self.exitB = QtWidgets.QPushButton(Form)
        self.exitB.setGeometry(QtCore.QRect(1620, 130, 221, 71))
        self.exitB.setStyleSheet("background-image: url(:/redc/lib/exit - Copy.png);\n"
"border:none;")
        self.exitB.setText("")
        self.exitB.setObjectName("exitB")
        self.pushButton.clicked.connect(self.signup)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(610, 790, 761, 211))
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 10);\n"
"font: 63 16pt \"Yu Gothic UI Semibold\";\n"
"color : white;")
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_5.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ffffff;\">23 OCT 2020</span></p></body></html>"))
import rec_rc
